Repository babelfish-for-postgresql/babelfish_project_website, pull requests merged in 2021-11, with the labels that each got.

#79 Fixing CI publishing
  .github/workflows/jekyll.yml
  README.md
  _config_CI.yml
Labels: bug

#88 Fix product name and a minor typo
  _installation/compiling-babelfish-from-source.md
Labels: documentation, typo

#83 Updated installation steps
  _installation/compiling-babelfish-from-source.md
Labels: documentation

#96 Adding build badge
  README.md
Labels: enhancement

#77 Change "lincense" -> "license" and add an article
  _docs/contributing.md
Labels: documentation

#92 Improve "vision" and "contributing" doc
  _docs/contributing.md
  _docs/vision.md
Labels: documentation

#98 Adding issue templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/question.yml
Labels: enhancement

#97 Auto generating CI config
  .github/workflows/jekyll.yml
  _config_CI.yml
Labels: enhancement

#81 Reorder system views alphabetically
  _internals/system-views.md
Labels: documentation

#78 Improve documentation "single-db" vs. "multi-db"
  _installation/single-multiple.md
Labels: documentation

#111 Improve the architecture documentation
  _internals/software-architecture.md
Labels: documentation

#116 Document how to access object from PostgreSQL
  _usage/migration.md
Labels: documentation

#113 Modified contributions.md to better match AWS open source guidelines
  _docs/contributing.md
Labels: documentation

#130 Address issue #120 migration page in documentation
  _usage/migration.md
Labels: WIP

#123 Removed the question template from ISSUE_TEMPLATE
  .github/ISSUE_TEMPLATE/question.yml
  _faq/getting_help.md
Labels: enhancement, In Review

#129 Improve the "limitations" page some more
  _usage/limitations-of-babelfish.md
Labels: documentation, In Review

#133 Replace "babelfish_money" documentation with a link
  _internals/software-architecture.md
Labels: documentation, In Review

#134 Improve user management documentation
  _usage/security.md
Labels: documentation

#139 Replace "MS SQL" with "Microsoft SQL Server"
  _client/csharp.md
  _client/java.md
  _faq/index.md
  _internals/babelfish-query-handling.md
  _internals/postgresql-hooks.md
  _internals/software-architecture.md
  _internals/system-views.md
  _internals/tds-protocol.md
  _usage/command-line.md
Labels: documentation

#141 Improve command line documentation
  _internals/configuration.md
  _usage/command-line.md
Labels: documentation

#143 Add a link to finish Babelfish setup
  _installation/compiling-babelfish-from-source.md
Labels: documentation, enhancement
